name: last-fm-now-playing

on:
  pull_request:
    paths:
      - "last-fm/now-playing/**"
      - ".github/workflows/last-fm-now-playing.yml"
      - ".github/workflows/lint-app.yml"
  push:
    branches: [main]
    paths:
      - "last-fm/now-playing/**"
      - ".github/workflows/last-fm-now-playing.yml"
      - ".github/workflows/deploy-app.yml"

jobs:
  lint:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/lint-app.yml
    with:
      app_path: last-fm/now-playing

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-app.yml
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      app_path: last-fm/now-playing
      service_name: lastfm-now-playing
      region: us-west1
      project_id: elliotx
      artifact_registry_repo: now-playing
      workload_identity_provider: projects/362369312254/locations/global/workloadIdentityPools/apps-github-pool/providers/apps-github-provider
      service_account: lastfm-now-playing-ci@elliotx.iam.gserviceaccount.com
