name: website-contact-form

on:
  pull_request:
    paths:
      - "website/contact-form/**"
      - ".github/workflows/website-contact-form.yml"
      - ".github/workflows/lint-app.yml"
  push:
    branches: [main]
    paths:
      - "website/contact-form/**"
      - ".github/workflows/website-contact-form.yml"
      - ".github/workflows/deploy-app.yml"

jobs:
  lint:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/lint-app.yml
    with:
      app_path: website/contact-form

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-app.yml
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      app_path: website/contact-form
      service_name: contact-form
      region: us-west1
      project_id: elliotx
      artifact_registry_repo: contact-form
      workload_identity_provider: projects/362369312254/locations/global/workloadIdentityPools/apps-github-pool/providers/apps-github-provider
      service_account: contact-form-ci@elliotx.iam.gserviceaccount.com
